version: 2
before:
  hooks:
    - go generate ./...
builds:
  - main: ./cmd/mdsend
    id: "mdsend"
    binary: mdsend
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - formats: ["zip"]
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^testdata"
homebrew_casks:
  - name: mdsend
    url:
      template: "https://github.com/dkotik/mdsend/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      using: ":homebrew_curl"
      verified: github.com/dkotik/mdsend/
    repository:
      owner: dkotik
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/dkotik/mdsend"
    description: "Send markdown files as MIME-encoded electronic mail."
    license: "MIT"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdsend"]
          end
signs:
  - id: cosign
    cmd: cosign
    args: ["sign-blob", "--bundle", "${signature}", "${artifact}", "--yes"]
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
